apiVersion: batch/v1
kind: Job
metadata:
  namespace: peerbie-prod
  name: db-migration
spec:
  template:
    spec:
      serviceAccountName: peerbie-gcr-sa
      containers:
      - name: migrate
        image: europe-west3-docker.pkg.dev/sage-nucleus-347914/peerbie-cr/migrations:latest
        volumeMounts:
            - name: gcs-credentials-volume
              mountPath: /app/apps/sim/service-account-key.json
              subPath: gcs-credentials # Match this with the key in your secret
            - name: google-cloud-key
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
        workingDir: /app/packages/db
        command: ['bun', 'run', 'db:migrate']
        envFrom:
        - secretRef:
            name: peerbie-studio-secret
      restartPolicy: Never
      volumes:
        - name: gcs-credentials-volume
          secret:
            secretName: gcs-credentials-secret
        - name: google-cloud-key
          projected:
            sources:
            - serviceAccountToken:
                path: token
                expirationSeconds: 3600 #adjust as needed