apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: peerbie-prod
  name: realtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime
  template:
    metadata:
      labels:
        app: realtime
    spec:
      serviceAccountName: peerbie-gcr-sa
      containers:
      - name: realtime
        image: europe-west3-docker.pkg.dev/sage-nucleus-347914/peerbie-cr/realtime:latest
        volumeMounts:
            - name: gcs-credentials-volume
              mountPath: /home/user/service-account-key.json
              subPath: gcs-credentials # Match this with the key in your secret
            - name: google-cloud-key
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
        envFrom:
        - secretRef:
            name: peerbie-studio-secret
        ports:
        - containerPort: 3002
          name: realtime-port
        resources:
          limits:
            memory: 2Gi
            cpu: 1000m
          requests:
            cpu: 500m
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /health
            port: realtime-port
          initialDelaySeconds: 40
          periodSeconds: 30
      volumes:
        - name: gcs-credentials-volume
          secret:
            secretName: gcs-credentials-secret
        - name: google-cloud-key
          projected:
            sources:
            - serviceAccountToken:
                path: token
                expirationSeconds: 3600 #adjust as needed
---
apiVersion: v1
kind: Service
metadata:
  name: realtime-service
spec:
  selector:
    app: realtime
  ports:
  - port: 80
    targetPort: 3002
  type: ClusterIP